dir = '/Users/Celeste/Desktop/polio-small-pop/polio-small-pop/'

library(RColorBrewer)

no_filter_fast_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_int_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_slow_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_fast_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_int_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_slow_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_fast_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_int_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_slow_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_fast_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_int_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_slow_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_fast_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_int_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_slow_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_fast_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_int_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_int_response_paper.out'), col.names=c('time', 'E&D'))
one_filter_slow_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_slow_response_paper.out'), col.names=c('time', 'E&D'))

marker = list(color = brewer.pal(8,"GnBu"))

png(paste0(dir,'Waning_on_ED_statistic_20000_response_paper.png'), width=1400, height=800, res=150)
plot(no_filter_fast_20000, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='Endemic potential statistic (probability of circulation)',xlim=c(0,10),col=marker$color[5])#start at 5 b/c its darker
lines(one_filter_fast_20000,type='l',lty=4, col = marker$color[5])
lines(no_filter_int_20000,type='l',lty=1, col=marker$color[6])
lines(one_filter_int_20000,type='l',lty=4, col=marker$color[6])
lines(no_filter_slow_20000,type='l',lty=1, col = marker$color[7])
lines(one_filter_slow_20000,type='l', lty=4,col = marker$color[7])
legend('topright', legend = c('ICA, fast waning (N=20,000)','no ICA, fast waning (N=20,000)', "ICA, intermediate waning (N=20,000)",'no ICA, intermediate waning (N=20,000)',"ICA, slow waning (N=20,000)",'no ICA, slow waning (N=20,000)'),col=c(marker$color[5],marker$color[5],marker$color[6],marker$color[6],marker$color[7],marker$color[7]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )
dev.off()

png(paste0(dir,'Waning_on_ED_statistic_10000_response_paper.png'), width=1400, height=800, res=150)
plot(no_filter_fast_10000, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='Endemic potential statistic (probability of circulation)',xlim=c(0,10),col=marker$color[5])
lines(one_filter_fast_10000,type='l',lty=4, col = marker$color[5])
lines(no_filter_int_10000,type='l', lty=1, col = marker$color[6])
lines(one_filter_int_10000,type='l',lty=4, col = marker$color[6])
lines(no_filter_slow_10000,type='l',lty=1, col = marker$color[7])
lines(one_filter_slow_10000,type='l', lty=4,col = marker$color[7])
legend('topright', legend = c('ICA, fast waning (N=10,000)','no ICA, fast waning (N=10,000)', "ICA, intermediate waning (N=10,000)",'no ICA, intermediate waning (N=10,000)',"ICA, slow waning (N=10,000)",'no ICA, slow waning (N=10,000)'),col=c(marker$color[5],marker$color[5],marker$color[6],marker$color[6],marker$color[7],marker$color[7]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )
dev.off()

png(paste0(dir,'Waning_on_ED_statistic_3500_response_paper.png'), width=1400, height=800, res=150)
plot(no_filter_fast_3500, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='Endemic potential statistic (probability of circulation)',xlim=c(0,10),col=marker$color[5])
lines(one_filter_fast_3500,type='l',lty=4, col = marker$color[5])
lines(no_filter_int_3500,type='l', lty=1, col = marker$color[6])
lines(one_filter_int_3500,type='l',lty=4, col = marker$color[6])
lines(no_filter_slow_3500,type='l', lty=1, col = marker$color[7])
lines(one_filter_slow_3500,type='l', lty=4,col = marker$color[7])
legend('topright', legend = c('ICA, fast waning (N=3500)','no ICA, fast waning (N=3500)', "ICA, intermediate waning (N=3500)",'no ICA, intermediate waning (N=3500)',"ICA, slow waning (N=3500)",'no ICA, slow waning (N=3500)'),col=c(marker$color[5],marker$color[5],marker$color[6],marker$color[6],marker$color[7],marker$color[7]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )
dev.off()

absRiskMat_20000_fast = read.csv(file=paste0(dir,'absolute_risk_matrix_N_20000.csv'),header=FALSE)
absRiskMat_20000_slow = read.csv(file=paste0(dir,'absolute_risk_matrix_N_20000_slow.csv'),header=FALSE)
absRiskMat_20000_int = read.csv(file=paste0(dir,'absolute_risk_matrix_N_20000_int.csv'),header=FALSE)
absRiskMat_5000_fast = read.csv(file=paste0(dir,'absolute_risk_matrix_N_5000.csv'),header=FALSE)
absRiskMat_5000_slow = read.csv(file=paste0(dir,'absolute_risk_matrix_N_5000_slow.csv'),header=FALSE)
absRiskMat_5000_int = read.csv(file=paste0(dir,'absolute_risk_matrix_N_5000_int.csv'),header=FALSE)

no_filter_fast_5000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_5000_beta_135_fast_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_slow_5000 = read.table(paste0(dir,'e_and_d_value-0pcase_det_1_N_5000_beta_200_fast_migrate_0_response_paper.out'), col.names=c('time', 'E&D'))
no_filter_int_5000 = read.table(paste0(dir,'e_and_d_value-0pcase_det_1_N_5000_beta_260_fast_migrate_0_response_paper.out'), col.names=c('time', 'E&D'))


png(paste0(dir,'Effect_of_waning_on_ED_statistic_N_20000_response_paper_absRisk.png'), width=1400, height=800, res=150)
par(mfrow=c(2,1),mar=c(0,3,0,0),oma=c(3,3,1,1),mgp=c(2,1,0))
plot(no_filter_fast_20000, type='l',lty=1, xlab = '',ylab = 'Probability of circulation',xlim=c(0,10),xaxt='n',col=marker$color[5])
lines(no_filter_int_20000,type='l', col=marker$color[6])
lines(no_filter_slow_20000,type='l', col=marker$color[7])
legend('topright', legend = c('fast waning (N=20000)','int waning (N=20000)',
                              'slow waning (N=20000)'),col=marker$color[5:7],lwd=2, bty='n' )
plot(absRiskMat_20000_fast[1:(nrow(absRiskMat_20000_beta_135)-4),], type='l',lty=1, xlab="Time since last paralytic case (years)",ylab="Absolute risk of circulation",yaxt='n',ylim=c(-.025,.01),xlim=c(0,10),col=marker$color[5])
lines(absRiskMat_20000_int,type='l', col=marker$color[6])
lines(absRiskMat_20000_slow[1:(nrow(absRiskMat_20000_beta_260)-1),],type='l', col=marker$color[7])
ticks<-c(-.02,-.01,0)
axis(2,at=ticks,labels=ticks)
abline(0,0)
legend('bottomright', legend = c('slow waning (N=20000)','int waning (N=20000)',
                                 'fast waning (N=20000)'),col=marker$color[5:7],lwd=2, bty='n' )
mtext("Time since last paralytic case (years)",side=1,line=2)
dev.off()

png(paste0(dir,'Effect_of_waning_on_ED_statistic_N_5000_response_paper_absRisk.png'), width=1400, height=800, res=150)
par(mfrow=c(2,1),mar=c(0,3,0,0),oma=c(3,3,1,1),mgp=c(2,1,0))
plot(no_filter_fast_5000, type='l',lty=1, xlab = '',ylab = 'Probability of circulation',xlim=c(0,10),xaxt='n',col=marker$color[5])
lines(no_filter_int_5000,type='l', col=marker$color[6])
lines(no_filter_slow_5000,type='l', col=marker$color[7])
legend('topright', legend = c('fast waning (N=5000)','int waning (N=5000)',
                              'slow waning (N=5000)'),col=marker$color[5:7],lwd=2, bty='n' )
plot(absRiskMat_5000_fast[1:(nrow(absRiskMat_5000_beta_135)-3),], type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='Absolute risk of circulation',xlim=c(0,10),col=marker$color[5],ylim=c(-.05,.05))
lines(absRiskMat_5000_int,type='l', col=marker$color[6])
lines(absRiskMat_5000_slow,type='l', col=marker$color[7])
abline(0,0)
legend('topright', legend = c('fast waning (N=5000)','int waning (N=5000)',
                              'slow waning (N=5000)'),col=marker$color[5:7],lwd=2, bty='n' )
mtext("Time since last paralytic case (years)",side=1,line=2)
dev.off()
