dir = '/Users/Celeste/Desktop/polio-small-pop/polio-small-pop/'

library(RColorBrewer)

no_filter_fast_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_fast.out'), col.names=c('time', 'E&D'))
no_filter_int_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_int.out'), col.names=c('time', 'E&D'))
no_filter_slow_10000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_10000_beta_135_slow.out'), col.names=c('time', 'E&D'))
one_filter_fast_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_fast.out'), col.names=c('time', 'E&D'))
one_filter_int_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_int.out'), col.names=c('time', 'E&D'))
one_filter_slow_10000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_10000_beta_135_slow.out'), col.names=c('time', 'E&D'))
no_filter_fast_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_fast.out'), col.names=c('time', 'E&D'))
no_filter_int_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_int.out'), col.names=c('time', 'E&D'))
no_filter_slow_3500 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_3500_beta_135_slow.out'), col.names=c('time', 'E&D'))
one_filter_fast_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_fast.out'), col.names=c('time', 'E&D'))
one_filter_int_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_int.out'), col.names=c('time', 'E&D'))
one_filter_slow_3500 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_3500_beta_135_slow.out'), col.names=c('time', 'E&D'))
no_filter_fast_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_fast.out'), col.names=c('time', 'E&D'))
no_filter_int_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_int.out'), col.names=c('time', 'E&D'))
no_filter_slow_20000 = read.table(paste0(dir,'e_and_d_values-0pcase_filter_det_1_N_20000_beta_135_slow.out'), col.names=c('time', 'E&D'))
one_filter_fast_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_fast.out'), col.names=c('time', 'E&D'))
one_filter_int_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_int.out'), col.names=c('time', 'E&D'))
one_filter_slow_20000 = read.table(paste0(dir,'e_and_d_values-1pcase_filter_det_1_N_20000_beta_135_slow.out'), col.names=c('time', 'E&D'))

marker = list(color = brewer.pal(8,"GnBu"))

png(paste0(dir,'Waning_on_ED_statistic_20000.png'), width=1400, height=800, res=150)
plot(no_filter_fast_20000, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='E&D stat (probability of circulation)',xlim=c(0,10),col=marker$color[3])#start at 3 b/c its darker
lines(one_filter_fast_20000,type='l',lty=4, col = marker$color[3])
lines(no_filter_int_20000,type='l',lty=1, col=marker$color[4])
lines(one_filter_int_20000,type='l',lty=4, col=marker$color[4])
lines(no_filter_slow_20000,type='l',lty=1, col = marker$color[5])
lines(one_filter_slow_20000,type='l', lty=4,col = marker$color[5])
legend('topright', legend = c('ICA, fast waning','no ICA, fast waning', "ICA, intermediate waning",'no ICA, intermediate waning',"ICA, slow waning",'no ICA, slow waning'),col=c(marker$color[3],marker$color[3],marker$color[4],marker$color[4],marker$color[5],marker$color[5]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )
dev.off()

png(paste0(dir,'Waning_on_ED_statistic_10000.png'), width=1400, height=800, res=150)
plot(no_filter_fast_10000, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='E&D stat (probability of circulation)',xlim=c(0,10),col=marker$color[3])
lines(one_filter_fast_10000,type='l',lty=4, col = marker$color[3])
lines(no_filter_int_10000,type='l', lty=1, col = marker$color[4])
lines(one_filter_int_10000,type='l',lty=4, col = marker$color[4])
lines(no_filter_slow_10000,type='l',lty=1, col = marker$color[5])
lines(one_filter_slow_10000,type='l', lty=4,col = marker$color[5])
legend('topright', legend = c('ICA, fast waning','no ICA, fast waning', "ICA, intermediate waning",'no ICA, intermediate waning',"ICA, slow waning",'no ICA, slow waning'),col=c(marker$color[3],marker$color[3],marker$color[4],marker$color[4],marker$color[5],marker$color[5]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )
dev.off()

png(paste0(dir,'Waning_on_ED_statistic_3500.png'), width=1400, height=800, res=150)
plot(no_filter_fast_3500, type='l',lty=1, xlab='Time since last paralytic case (years)', ylab='E&D stat (probability of circulation)',xlim=c(0,10),col=marker$color[3])
lines(one_filter_fast_3500,type='l',lty=4, col = marker$color[3])
lines(no_filter_int_3500,type='l', lty=1, col = marker$color[4])
lines(one_filter_int_3500,type='l',lty=4, col = marker$color[4])
lines(no_filter_slow_3500,type='l', lty=1, col = marker$color[5])
lines(one_filter_slow_3500,type='l', lty=4,col = marker$color[5])
legend('topright', legend = c('ICA, fast waning','no ICA, fast waning', "ICA, intermediate waning",'no ICA, intermediate waning',"ICA, slow waning",'no ICA, slow waning'),col=c(marker$color[3],marker$color[3],marker$color[4],marker$color[4],marker$color[5],marker$color[5]),lwd=2,lty=c(1,4,1,4,1,4), bty='n' )

dev.off()